Controllers/AnnouncementsController.cs
using FirstMVCApp.Models;
using FirstMVCApp.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.Controllers
{
    public class AnnouncementsController : Controller
    {
        private readonly AnnouncementsRepository _repository;

        public AnnouncementsController(AnnouncementsRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            var announcements = _repository.GetAnnouncements();
            return View("Index", announcements);
        }

        public IActionResult Create() 
        { 
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(IFormCollection collection)
        {
            AnnouncementModel model = new AnnouncementModel();          // se creaza un model nou pentru inserarea in baza de date
            TryUpdateModelAsync(model);                                 // mapeaza datele din colectie - formular - pe modelul creat local
            _repository.Add(model);                                     // se transmite modelul spre ORM

            
            return RedirectToAction("Index");
        }
        public IActionResult Edit(Guid id) 
        { 
            var model = _repository.GetAnnouncementById(id);
            return View("Edit", model);
        }

        [HttpPost]
        public IActionResult Edit(IFormCollection collection)
        {
            AnnouncementModel model = new();
            TryUpdateModelAsync(model);
            _repository.Update(model);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(Guid id, IFormCollection collection) 
        {
           var model = _repository.GetAnnouncementById(id);
           return View("Delete", model);
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            _repository.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Details(Guid id) 
        { 
            return View("Details", _repository.GetAnnouncementById(id));
        }
    }
}

Controllers/CodeSnippetsController.cs
using FirstMVCApp.Models;
using FirstMVCApp.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.Controllers
{
    public class CodeSnippetsController : Controller
    {
        private readonly CodeSnippetsRepository _repository;
        private readonly MembersRepository _membersRepository;

        public CodeSnippetsController(CodeSnippetsRepository repository, MembersRepository membersRepository)
        {
            _repository = repository;
            _membersRepository = membersRepository;
        }

        // GET: CodeSnippets
        public ActionResult Index()
        {
            var codeSnippets = _repository.GetAll();
            return View("Index", codeSnippets);
        }

        // GET: CodeSnippets/Details/5
        public ActionResult Details(Guid id)
        {
            var codeSnippet = _repository.GetById(id);
            return View("Details", codeSnippet);
        }

        // GET: CodeSnippets/Create
        public ActionResult Create()
        {
            var members = _membersRepository.GetMembers();
            ViewBag.data = members;
            return View("Create");
        }

        // POST: CodeSnippets/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            var model = new CodeSnippetModel();
            TryUpdateModelAsync(model);
            _repository.Add(model);

            return RedirectToAction("Index");
        }

        // GET: CodeSnippets/Edit/5
        public ActionResult Edit(Guid id)
        {
            return View("Edit", _repository.GetById(id));
        }

        // POST: CodeSnippets/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, IFormCollection collection)
        {
            var model = new CodeSnippetModel();
            TryUpdateModelAsync(model);
            _repository.Update(model);
            return RedirectToAction("Index");
        }

        // GET: CodeSnippets/Delete/5
        public ActionResult Delete(Guid id)
        {
            return View("Delete", _repository.GetById(id));
        }

        // POST: CodeSnippets/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            _repository.DeleteById(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/MembersController.cs
using FirstMVCApp.Models;
using FirstMVCApp.Repositories;
using FirstMVCApp.VuewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace FirstMVCApp.Controllers
{
    public class MembersController:Controller
    {
        private readonly MembersRepository _repository;

        public MembersController(MembersRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            var members = _repository.GetMembers();
            return View("Index", members);
        }

        public IActionResult Create()
        {
            return View("CreateMember");
        }

        [HttpPost]
        public IActionResult CreateMember(IFormCollection members) 
        { 
            MemberModel model = new MemberModel();
            TryUpdateModelAsync(model);
            _repository.AddMember(model);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(Guid id) 
        {
            return View("Edit", _repository.GetMemberById(id));
        }

        [HttpPost]
        public IActionResult Edit(IFormCollection collection) 
        {
            MemberModel member = new MemberModel();
            TryUpdateModelAsync(member);
            _repository.UpdateMember(member);


            return RedirectToAction("Index");
        }

        public IActionResult Details(Guid id) 
        {
            return View("Details", _repository.GetMemberById(id));
        }

        [HttpGet]
        public IActionResult Delete(Guid id) 
        {
            return View("Delete", _repository.GetMemberById(id));
        }

        [HttpPost]
        public IActionResult Delete(Guid id, IFormCollection collection) 
        {          
           _repository.DeleteMemberById(id);
            return RedirectToAction("Index");
        }

        public  IActionResult DetailsWithCodeSnippets(Guid id)
        {
            MemberCodeSnippetsViewModel viewModel = _repository.GetMemberCodeSnippets(id);  
            return View("DetailsWithCodeSnippets", viewModel);
        }
    }
}

Controllers/MembershipTypesController.cs
using FirstMVCApp.Models;
using FirstMVCApp.Repositories;
using FirstMVCApp.VuewModels;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;

namespace FirstMVCApp.Controllers
{
    public class MembershipTypesController : Controller
    {
        private readonly MembershipTypesRepository _repository;

        public MembershipTypesController(MembershipTypesRepository repository)
        {
            _repository = repository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var memberships = _repository.GetAll();
            return View("Index", memberships);
        }

        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(IFormCollection collection)
        {
            var model = new MembershipTypeModel();
            TryUpdateModelAsync(model);
            _repository.AddMembershiptType(model);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(Guid id)
        {
            var membership = _repository.FindById(id);
            return View("Edit", membership);
        }

        [HttpPost]
        public IActionResult Edit(Guid id, IFormCollection collection)
        {
            var updatedMembership = new MembershipTypeModel();
            TryUpdateModelAsync(updatedMembership);

            _repository.UpdateMembershipType(id, updatedMembership);

            return RedirectToAction("Index");
        }

        public IActionResult Details(Guid id)
        {
            return View("Details", _repository.FindById(id));
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            var model = _repository.FindById(id);
            return View("Delete", model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id, IFormCollection collection) 
        { 
            _repository.DeleteMembershipType(_repository.FindById(id));
            return RedirectToAction("Index");
        }      
        
        public IActionResult DetailsByMembershipType(Guid id)
        {
            MembershipTypesMembersViewModel model = _repository.GetMembersByMembership(id);
            return View("DetailsByMembershipType", model);
        }
    }
}

Views/Shared/DeleteModal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstMVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstMVCApp.styles.css" asp-append-version="true" />
</head>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstMVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstMVCApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FirstMVCApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Announcements" asp-action="Index">Announcements</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Memberships" asp-action="Index">Memberships</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MembershipTypes" asp-action="Index"> Membership Types</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CodeSnippets" asp-action="Index">Code Snippets</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FirstMVCApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>